/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.zumium.boxes.thrift;


public enum BoxStatus implements org.apache.thrift.TEnum {
  OPEN(0),
  ARCHIVED(1);

  private final int value;

  private BoxStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BoxStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return OPEN;
      case 1:
        return ARCHIVED;
      default:
        return null;
    }
  }
}
